project:
  type: website

website:
  title: "subcell-correlation"
  navbar:
    left:
      - href: alignment.qmd
        text: Alignment
      - href: comparison.qmd
        text: Comparison
      - href: summary.qmd
        text: Summary
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

